### ISSUE TITLE
[Bugs?] Failed to connect to WebConsole of free5GC v3.0.5

### ISSUE THREAD

**Issue by s5uishida** [free5gc/free5gc#167]
Hi everyone,

https://github.com/free5gc/free5gc/wiki/Appendix

While referring to the above URL, when I started WebConsole with v3.0.5 and tried to connect from the browser, the following was displayed on the browser. 
```
404 page not found
```
In addition, the following log was output to the WebConsole log. 
```
2021-01-31T12:06:00Z [INFO][WebUI][GIN] | 404 |   192.168.0.101 | GET     | / |
2021-01-31T12:06:00Z [INFO][WebUI][GIN] | 404 |   192.168.0.101 | GET     | /favicon.ico |
```
On the other hand, in the case of v3.0.4, the login screen was displayed properly, and the following log was output to the WebConsole log. 
```
2021-01-31T11:58:31Z [INFO][WebUI][GIN] | 200 |   192.168.0.101 | GET     | / |
2021-01-31T11:58:31Z [INFO][WebUI][GIN] | 200 |   192.168.0.101 | GET     | /static/js/main.69cbf67c.js |
2021-01-31T11:58:31Z [INFO][WebUI][GIN] | 200 |   192.168.0.101 | GET     | /static/media/free5gc_logo.adcdb325.png |
2021-01-31T11:58:31Z [INFO][WebUI][GIN] | 200 |   192.168.0.101 | GET     | /favicon.ico |
```
Please let me know how to use the Web Console of v3.0.5.

Thank you very much in advance.

**Comment by shigeki-yamano** [comment]
In the case of v3.0.5, you can run webconsole server as follows.

```
cd ~/free5gc/webconsole/bin
./webconsole
```

**Comment by s5uishida** [comment]
Hi @shigeki-yamano 

I was able to use the WebConsole.
Thank you very much for your information.

For the time being, I will write the procedure at that time below. 

**1) Prior to building webconsole, install nodejs and yarn package first as follows:**
```
https://github.com/free5gc/webconsole
```
```
sudo apt remove cmdtest
sudo apt remove yarn
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update
sudo apt-get install -y nodejs yarn
```
**2) Build WebConsole**
It seems that 2GB or more of OS memory is recommended. I could not build WebConsole with 1GB memory. 
```
cd ~/free5gc
make webconsole
```
**3) Start WebConsole**
```
cd ~/free5gc/webconsole/bin
./webconsole
```
I connected to `http://ip-address:5000/` with a browser.

**Comment by free5gc-org** [comment]
@s5uishida 

We updated the README in webconsole.
And also thanks for the procedure, we'll update on the wiki installation.

**Comment by noormohammedli** [comment]
Hello @s5uishida,
I did all the steps that you said and still not working and I have a problem in  make webconsole:


$ make webconsole
Start building webconsole....
cd webconsole/frontend && \
yarn install && \
yarn build && \
rm -rf ../public && \
cp -R build ../public
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
make: *** [Makefile:62: webconsole/bin/webconsole] Error 1

Thanks
Noor

**Comment by s5uishida** [comment]
Hi @noormohammedli 

I'm using WebConsole on Ubuntu 20.04 as below.

https://github.com/free5gc/free5gc/wiki/Installation#d-install-webconsole
```
# cd ~/free5gc
# make webconsole
# cd webconsole/bin
# ./webconsole
```
