### ISSUE TITLE
[Bugs]ULCL multi-UPF: “Mod CreateURR error: file exists” on I-UPF when attaching UE

### ISSUE THREAD

**Issue by haha39** [free5gc/free5gc#721]
**Environment**
- free5GC version: **v4.1.0**
- UERANSIM version: **v3.2.7**
- OS: **Ubuntu 20.04.6 LTS (Focal Fossa)**
- gtp5g: **v0.9.14**

**Topology**
- Path 1: gNB1 → I-UPF1 → PSA-UPF1
- Path 2: gNB2 → I-UPF2 → PSA-UPF2
- MEC1 and MEC2 connected for local breakout through I-UPF1 and I-UPF2 (ULCL)
- Each path uses a different S-NSSAI

**Problem**
When attaching a UE (either in Path 1 or Path 2), sometimes the I-UPF/I-UPF2 shows:
```less
[ERRO][UPF][PFCP][LAddr:<IUPF_IP>][CPNodeID:<SMF_IP>] Mod CreateURR error: file exists
```
When this happens, PSA-UPF/PSA-UPF2 does not show the usual `[INFO] New session`.
All network functions are deployed on separate VMs: gNB1, gNB2, 5GC, I-UPF1, I-UPF2, PSA-UPF1, PSA-UPF2, MEC1, MEC2.

**Configuration & Logs**
I have uploaded the requested files and logs to gist for better readability:
[smfcfg.yaml](https://gist.github.com/haha39/870dcda09b3579b279f78f90633956c5#file-smfcfg-yaml)
[uerouting.yaml](https://gist.github.com/haha39/870dcda09b3579b279f78f90633956c5#file-uerouting-yaml)
[i-upf.yaml](https://gist.github.com/haha39/1e340f81b46483435f849a4349c1d617#file-i-upf-yaml)
[psa-upf.yaml](https://gist.github.com/haha39/1e340f81b46483435f849a4349c1d617#file-psa-upf-yaml)
[I-UPF log](https://gist.github.com/haha39/086cacb2b4f9a41b85e87d2f9a5e5860#file-i-upf-log)
[PSA-UPF log](https://gist.github.com/haha39/086cacb2b4f9a41b85e87d2f9a5e5860#file-psa-upf-log)

**Comment by Alonza0314** [comment]
Hi @haha39 ,
This error log is an incorrect log. It should be a "WARN" log.  We have corrected it in the UPF repo.
Did you met any functional err?

The reason for update the log type from ERROR to WARN is that the URR can be used by multi-sessions. It will not be created if the same URR already existed.

By the way, we have located issue#708's error and is fixing now.

Alonza

**Comment by hokusai0603** [comment]
#Hi @Alonza0314 ,
I'm a member in @haha39's team, and I'm currently looking into this issue.  After some test in the environment above with only the version of free5gc updated to 4.1.0, I still encounter the same issue and in the same format as mentioned above. I'll provide the log of the 5g core, psa-upf, and i-upf respectively.  Since that you said you already updated in 4.1.0, I'm sort of curious whether you got any kinds of preliminary thoughts about this situation?
The error log shown in the i-upf looks like this: 

`2025-09-28T05:14:22.406457674Z [ERRO][UPF][PFCP][LAddr:<IUPF_IP>][CPNodeID:<SMF_IP>][CPSEID:0x1][UPSEID:0x1] Mod CreateURR error: file exists`

Hope the things I provide here help, thank you !

[uerouting.yaml](https://gist.github.com/hokusai0603/6e0e443b411307fdf185b420285d4deb#file-uerouting-yaml)
[smfcfg.yaml](https://gist.github.com/hokusai0603/6e0e443b411307fdf185b420285d4deb#file-smfcfg-yaml)
[I-UPF.yaml](https://gist.github.com/hokusai0603/6e0e443b411307fdf185b420285d4deb#file-i-upf-yaml)
[PSA-UPF.yaml](https://gist.github.com/hokusai0603/6e0e443b411307fdf185b420285d4deb#file-psa-upf-yaml)
[i-upf.log](https://gist.github.com/hokusai0603/6e0e443b411307fdf185b420285d4deb#file-i-upf-log)
[psa-upf.log](https://gist.github.com/hokusai0603/6e0e443b411307fdf185b420285d4deb#file-psa-upf-log)
[5gc.log](https://gist.github.com/hokusai0603/6e0e443b411307fdf185b420285d4deb#file-5gc-log)
# # #

**Comment by Alonza0314** [comment]
Hi @hokusai0603 ,

The log type is updated after v4.1.0 released and haven't sync to free5GC's main repo. You can try to use the newest version of UPF with these commands:

```bash
git clone -j `nproc` --recursive https://github.com/free5gc/free5gc
cd free5gc/NFs/upf
git checkout main
git pull origin main
cd ../../
make
```

Given your situation, it's expected to see only log errors without any actual functional issues. If you do encounter a functional problem, I'm happy to help investigate it further. Thank you

**Comment by hokusai0603** [comment]
Hi @Alonza0314 ,
Thanks for the quick response, I'll update and try in the main branch from now. Will update here if anything new is found, Huge thanks here !

**Comment by hokusai0603** [comment]
Hi @Alonza0314 ,
I have confirmed that the log was change to warning instead of error. But the issue that I'm trying to address is that whenever this error/warning message appears, the registration of the UE will not be well executed. Since PSA-UPF will not receive any info about this action as mentioned above. Which makes UE unable to access to the public network as it's intended to.

What's interesting is, it happenes "occationally", which makes it harder to address. I'll provide some footage where this happened and you'll see how it act under this circumstance.

All experiment was conducted with the config mentioned above. Nothing have been changed during the process.
[When this issue happens](https://youtu.be/FAKRbgn68kY)
[When this issue happens 2](https://youtu.be/Abo3Q9GugUg)
[How it's intend to work](https://youtu.be/tTC4sScxnfY)

Thanks for the time and hope this will address this problem more clearly！

**Comment by Alonza0314** [comment]
Hi @hokusai0603 ,

I think this issue is same as before. (#708)
Our teammate has located the error around the UPFs path decision. But it still needs some time to fix it.
We're working on it😵‍💫.

Alonza

**Comment by Alonza0314** [comment]
Hi @haha39 @hokusai0603 ,

I've fixed this at https://github.com/free5gc/smf/pull/178. I'll close this issue first. Issue#708 will be closed after the PR merged.

Thanks for your waiting

Alonza

**Comment by hokusai0603** [comment]
Hi @Alonza0314 ,
We still face the same situation after weeks of testing, and the behavior of the whole system is the same as mentioned before ( in the exact same setting ).  Haven't been able to locate the root cause of the problem, but would like to ask for help if there's any possible cause of this issue.
Thanks!

Hokusai0603

**Comment by Alonza0314** [comment]
Hi @hokusai0603 ,

I found that you're using host to deploy the system. Can you try it on a single machine with docker? It works well in my test every time with docker on a single machine even with the URR warn. This is to check if it is the network link problem.

Also, I think we can try to get the `dmesg` with `sudo dmesg -w` on both I-UPF and PSA-UPF to see if gtp5g drops the packet or not.

Alonza0314

**Comment by hokusai0603** [comment]
Hi @Alonza0314 ,

Thanks for the quick reply as always, we will try to test in the enviroment mentioned above.

Hokusai0603

**Comment by hokusai0603** [comment]
Hi @Alonza0314 ,

After some behavior tracing in SMF, I found that the unexpected behavior in the UE registration flow was due to a misconfiguration in smfcfg.yaml. Setting both I-UPFs and PSA-UPFs’ dnn to ‘internet’ makes the path selection algorithm in user_plane_information.go sometimes chose I-UPF as its destination. Thus causing the problem mentioned above. The ‘Duplicate URR creation’ was not the root cause of the issue, but just a warning log that pops up as a result. So I think this issue was misdefined from the beginning and can be closed as solved for now!

That’s about the research I have done during this time period. If you have any comments or something to add as the conclusion, I’m more than happy to know more about the mechanism behind free5GC!

Once again. Thanks for all the help and the effort invested into this issue I had!

Hokusai0603

**Comment by Alonza0314** [comment]
Hi Hokusai0603,

Thanks for the clarification! Everything looks good from my side.

I'll close this issue now. If there is anything we can help, please feel free to open issue!

Alonza
